"""Atomic promotion for files generated by the pipeline."""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path


@contextmanager
def atomic_path(path: Path) -> Iterator[Path]:
    """Yield a sibling temporary path and promote it after successful writing."""

    temporary = path.with_name(f".{path.name}.tmp")
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary.unlink(missing_ok=True)
    try:
        yield temporary
        temporary.replace(path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise
