"""Hugging Face staging with an explicit compact-artifact boundary."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pyarrow.parquet as pq

from osm_polygon_wikidata_website_coverage.pipeline.aggregate import EXPECTED_GLOBAL_COLUMNS

TARGET_REPOSITORY = "NoeFlandre/osm-polygon-wikidata-website-coverage-stats"
_FORBIDDEN_FIELDS = {
    "geometry",
    "website_text",
    "contact_website_text",
    "full_text",
    "text",
    "raw_pbf",
    "credentials",
}


class PublicationBoundaryError(ValueError):
    """Raised when staging would publish data outside the approved boundary."""


def _check_completed_run(run_root: Path) -> None:
    manifest = run_root / "manifests" / "manifest.json"
    if not manifest.is_file():
        raise PublicationBoundaryError(f"completed manifest is missing: {manifest}")
    try:
        payload = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise PublicationBoundaryError(f"completed manifest is not valid JSON: {manifest}") from exc
    if payload.get("status") != "complete":
        raise PublicationBoundaryError("run manifest is not complete")


def _parquet_files(directory: Path, description: str) -> tuple[Path, ...]:
    if not directory.is_dir():
        raise PublicationBoundaryError(f"{description} directory is missing: {directory}")
    files = tuple(sorted(directory.glob("*.parquet"), key=lambda path: path.name))
    if not files:
        raise PublicationBoundaryError(f"{description} directory contains no Parquet files")
    return files


def _validate_schema(path: Path, *, is_global: bool) -> None:
    names = pq.read_schema(path).names
    forbidden = _forbidden_fields(names)
    if forbidden:
        raise PublicationBoundaryError(f"{path} contains forbidden fields: {', '.join(forbidden)}")
    if is_global:
        _validate_global_schema(path, names)


def _forbidden_fields(names: list[str]) -> list[str]:
    return sorted(name for name in names if name in _FORBIDDEN_FIELDS)


def _validate_global_schema(path: Path, names: list[str]) -> None:
    if set(names) != set(EXPECTED_GLOBAL_COLUMNS):
        raise PublicationBoundaryError(f"{path} does not match the compact global schema")


def _repository_file(name: str) -> Path:
    path = Path(__file__).parents[3] / name
    if not path.is_file():
        raise PublicationBoundaryError(f"repository publication file is missing: {path}")
    return path


def _dataset_card(run_id: str) -> str:
    return f"""---
license: odbl
task_categories:
  - tabular-classification
tags:
  - openstreetmap
  - wikidata
  - wikipedia
  - wikivoyage
pretty_name: OSM polygon text coverage
---

# OSM polygon text coverage

This dataset contains compact derived evidence for coverage of the valid raw
OpenStreetMap polygon universe by successful website, Wikipedia, and Wikivoyage
text records. It was generated by run `{run_id}`.

The global Parquet shards contain OSM identity and provenance, geometry type and
descriptive metrics, three independent Boolean source flags, and one of eight
mutually exclusive overlap categories. Summary Parquets contain global,
per-source-PBF, per-region, overlap, geometry-failure, and conflict statistics.

No raw PBF bytes, full geometry, fetched website text, Wikipedia text,
Wikivoyage text, fetch cache, credential, or private run state is included.

## Licensing

The derived polygon evidence is based on OpenStreetMap data and is available
under the Open Database License (ODbL), with OpenStreetMap attribution. The
analysis code and documentation are Apache-2.0. This artifact republishes no
fetched source text.

See `ATTRIBUTION.md` for limitations and attribution details.
"""


def _attribution() -> str:
    return """# Attribution and limitations

Polygon identities and geometry descriptors are derived from OpenStreetMap
data. OpenStreetMap data is © OpenStreetMap contributors and is available under
the Open Database License (ODbL). See https://www.openstreetmap.org/copyright.

The website, Wikipedia, and Wikivoyage datasets were read as external
membership predicates. Successful-text content is not included in this
dataset. Counts are scoped to the supplied raw PBF inventory, source dataset
versions, geometry validation rules, and run manifest.
"""


def _prepare_destination(destination: Path) -> None:
    if destination.exists() and any(destination.iterdir()):
        raise PublicationBoundaryError("HF staging destination must be empty")
    destination.mkdir(parents=True, exist_ok=True)


def _staging_files(
    run_root: Path,
) -> tuple[tuple[Path, ...], tuple[Path, ...]]:
    return (
        _parquet_files(run_root / "coverage" / "global", "global coverage"),
        _parquet_files(run_root / "summaries", "summary"),
    )


def _validate_staging_files(
    global_files: tuple[Path, ...], summary_files: tuple[Path, ...]
) -> None:
    for path in global_files:
        _validate_schema(path, is_global=True)
    for path in summary_files:
        _validate_schema(path, is_global=False)


def _copy_staging_files(
    destination: Path,
    global_files: tuple[Path, ...],
    summary_files: tuple[Path, ...],
) -> None:
    for source, relative_root in (
        (global_files, Path("data/coverage/global")),
        (summary_files, Path("data/summaries")),
    ):
        target_root = destination / relative_root
        target_root.mkdir(parents=True, exist_ok=True)
        for path in source:
            shutil.copy2(path, target_root / path.name)


def _copy_summary_json(run_root: Path, destination: Path) -> None:
    summary_json = run_root / "reports" / "summary.json"
    if summary_json.is_file():
        shutil.copy2(summary_json, destination / "data" / "summary.json")


def stage_hf(run_root: Path, destination: Path) -> Path:
    """Stage only compact coverage and summary artifacts for Hugging Face."""

    run_root = run_root.absolute()
    destination = destination.absolute()
    _check_completed_run(run_root)
    _prepare_destination(destination)
    global_files, summary_files = _staging_files(run_root)
    _validate_staging_files(global_files, summary_files)
    _copy_staging_files(destination, global_files, summary_files)
    _copy_summary_json(run_root, destination)
    run_id = json.loads((run_root / "manifests" / "manifest.json").read_text(encoding="utf-8")).get(
        "run_id", run_root.name
    )
    (destination / "README.md").write_text(_dataset_card(str(run_id)), encoding="utf-8")
    shutil.copy2(_repository_file("CITATION.cff"), destination / "CITATION.cff")
    shutil.copy2(_repository_file("LICENSE"), destination / "LICENSE")
    (destination / "ATTRIBUTION.md").write_text(_attribution(), encoding="utf-8")
    return destination
